# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: nitroshkin/db-person:${APP_VERSION}
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: dev
      POSTGRES_DB: personservice
      PGDATA: /home/data
      POSTGRES_INITDB_ARGS: "-A md5"
    expose:
      - 5432
    ports:
      - "54321:5432"
    volumes:
      - pg_data_volume:/data/lib/postgresql/data

  server:
    image: nitroshkin/server-person:${APP_VERSION}
    container_name: server
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/persons || exit 1
      interval: 1s
      retries: 10
      start_period: 0s
      timeout: 10s

volumes:
  pg_data_volume:



