name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - server
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: nitroshkin/server-person
  DB_IMAGE_NAME: nitroshkin/db-person
  APP_VERSION: ${{ github.run_number }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  VM_IP: 87.239.104.225
  VM_USER: ubuntu
  WORKDIR: /home/ubuntu/ps_deploy
  PG_USER: dev
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}


jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Server
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
          docker build --quiet -t $IMAGE_NAME:$APP_VERSION ./app/server/PersonServer
          docker push $IMAGE_NAME:$APP_VERSION
          docker build --quiet -t $DB_IMAGE_NAME:$APP_VERSION ./app/sql
          docker push $DB_IMAGE_NAME:$APP_VERSION

      - name: Unit Tests
        run: |
          cd ./app/server/PersonServer && mvn clean -e -Dtest=*Test test

      - name: Deploy
        run: |
            chmod 400 ./app/deploy/Ubuntu-Standard-2-2-20GB-lObZWNiy.pem
            echo "APP_VERSION=$APP_VERSION" >> .env
            echo "PG_USER=$PG_USER" >> .env
            echo "PG_PASSWORD=$PG_PASSWORD" >> .env
            chmod 400 ./app/deploy/ps_id_rsa
            ssh -o StrictHostKeyChecking=no -i ./app/deploy/ps_id_rsa $VM_USER@$VM_IP "mkdir -p ps_deploy"
            scp -i ./app/deploy/ps_id_rsa .env $VM_USER@$VM_IP:$WORKDIR/.env
            scp -i ./app/deploy/ps_id_rsa ./app/docker-compose.yml $VM_USER@$VM_IP:$WORKDIR/docker-compose.yml
            ssh -o StrictHostKeyChecking=no -i ./app/deploy/ps_id_rsa $VM_USER@$VM_IP "
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin &&
            cd $WORKDIR &&
            docker-compose up -d"
            ssh -o StrictHostKeyChecking=no -i ./app/deploy/ps_id_rsa $VM_USER@$VM_IP "timeout 90s bash -c \"until docker exec database pg_isready ; do sleep 1 ; done\""
            ssh -o StrictHostKeyChecking=no -i ./app/deploy/ps_id_rsa $VM_USER@$VM_IP "timeout 90s bash -c \"while [ \\\"\\\`docker inspect -f {{.State.Health.Status}} server\\\`\\\" != \\\"healthy\\\" ]; do sleep 1; echo a ; done\""

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      #- name: Github auto grader mark
      #  uses: Romanow/google-sheet-autograder-marker@v1.0
      #  with:
      #    google_token: ${{secrets.GOOGLE_API_KEY}}
      #    sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
      #    homework_number: 1
      #    user_column: 'D'
      #    column_offset: 'F'
      #    mark: "'+"